# Uncomment the next line to define a global platform for your project
# platform :ios, '15.1'

target 'Test-Assignment-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-Assignment-iOS
pod 'Swinject'
pod 'CombineCocoa'

end
